/*
    try {
        Código que puede fallar 
    } catch (error) {
        Qué hacer cuando ese código fallé 
    }
*/

/*function dividirNumeros (a: number, b: number) {
  
    
    try {
         if (b === 0)
            throw new Error ('No es posible dividir por 0   ')
        return a / b
    } catch (error) {
      
        if  (error instanceof Error) console.log('Error: ', error.message)
        return -1
    }

}

*/
